// <auto-generated />
using MediumBooks.Users;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediumBooks.Users.Data.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20240505160422_UsersSeedingMigration")]
    partial class UsersSeedingMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("user")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediumBooks.Users.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users", "user");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Name = "Name 1",
                            Password = "password1"
                        },
                        new
                        {
                            UserId = 2,
                            Name = "Name 2",
                            Password = "password2"
                        },
                        new
                        {
                            UserId = 3,
                            Name = "Name 3",
                            Password = "password3"
                        },
                        new
                        {
                            UserId = 4,
                            Name = "Name 4",
                            Password = "password4"
                        },
                        new
                        {
                            UserId = 5,
                            Name = "Name 5",
                            Password = "password5"
                        },
                        new
                        {
                            UserId = 6,
                            Name = "Name 6",
                            Password = "password6"
                        },
                        new
                        {
                            UserId = 7,
                            Name = "Name 7",
                            Password = "password7"
                        },
                        new
                        {
                            UserId = 8,
                            Name = "Name 8",
                            Password = "password8"
                        },
                        new
                        {
                            UserId = 9,
                            Name = "Name 9",
                            Password = "password9"
                        },
                        new
                        {
                            UserId = 10,
                            Name = "Name 10",
                            Password = "password10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
